name: alias-for-aiwg-regenerate-agents-regenerate-agents-md
description: "Alias for /aiwg-regenerate-agents - Regenerate AGENTS.md"
model:
  name: gpt-4
  temperature: 0.3
  max_tokens: 4000
instructions: |
  # Regenerate AGENTS.md (Factory Alias)
  
  > **Note:** This command is an alias for `/aiwg-regenerate-agents`.
  > Use `/aiwg-regenerate-agents` for the canonical command.
  
  This alias exists for backward compatibility. Both commands regenerate AGENTS.md.
  
  ## Usage
  
  ```text
  /aiwg-regenerate-factory
  # equivalent to:
  /aiwg-regenerate-agents
  ```
  
  ## See Also
  
  - `/aiwg-regenerate-agents` - The canonical command for AGENTS.md
  - `/aiwg-regenerate-claude` - Regenerate CLAUDE.md
  - `/aiwg-regenerate-warp` - Regenerate WARP.md
  - `/aiwg-regenerate` - Auto-detect platform