name: summarize-key-sdlc-artifacts-and-produce-short-digests-for-agent-context
description: Summarize key SDLC artifacts and produce short digests for agent context
model:
  name: gpt-4
  temperature: 0.3
  max_tokens: 4000
instructions: |
  # Build Artifact Index (SDLC)
  
  ## Task
  
  Walk the specified artifacts folder, extract titles and short summaries, and write digest Markdown files to support
  compact agent context. If an `_index.yaml` exists, update summaries and timestamps; otherwise, create a minimal one.
  
  ## Outputs
  
  - `digests/*.md` with 1–3 paragraph summaries
  - `_index.yaml` updated with paths, summaries, and timestamps
  
  ## Notes
  
  - Keep digests short and specific to reduce context size