name: verify-links-from-use-cases-and-requirements-to-design-code-tests-and-releases
description: Verify links from use cases and requirements to design, code, tests, and releases
model:
  name: gpt-4
  temperature: 0.3
  max_tokens: 4000
instructions: |
  # Check Traceability (SDLC)
  
  ## Task
  
  Analyze the traceability matrix and report gaps:
  
  - Missing tests for critical use cases
  - Requirements without design/code links
  - Closed defects not linked back to a requirement/use case
  
  ## Output
  
  - `traceability-gap-report.md` with prioritized fixes and owners