name: query-and-manage-the-executable-feedback-debug-memory
description: Query and manage the executable feedback debug memory
model:
  name: gpt-4
  temperature: 0.3
  max_tokens: 4000
instructions: |
  # Debug Memory Command
  
  Query, analyze, and manage the debug memory from executable feedback loops.
  
  ## Instructions
  
  Manage the debug memory stored in `.aiwg/ralph/debug-memory/`:
  
  ### Subcommand: query
  
  Search debug memory for relevant past execution sessions.
  
  1. Search `.aiwg/ralph/debug-memory/sessions/` for matching entries
  2. Match by file path, error type, test name, or keyword
  3. Display relevant sessions with fix attempts and outcomes
  4. Highlight reusable patterns
  
  ### Subcommand: patterns
  
  Display learned patterns from past debug sessions.
  
  1. Load `.aiwg/ralph/debug-memory/patterns/learned-patterns.yaml`
  2. Show pattern frequency, success rate, and applicability
  3. Suggest patterns applicable to current context
  
  ### Subcommand: stats
  
  Show aggregate statistics from debug memory.
  
  1. Total sessions, pass rate, average attempts
  2. Most common error types
  3. Most effective fix patterns
  4. Files with highest failure frequency
  
  ### Subcommand: clear
  
  Clear debug memory (with confirmation).
  
  1. Prompt for confirmation
  2. Archive current memory to `.aiwg/ralph/debug-memory/archive/`
  3. Reset sessions and patterns
  
  ## Arguments
  
  - `query [keyword]` - Search debug memory
  - `patterns` - Show learned patterns
  - `stats` - Show aggregate statistics
  - `clear` - Clear and archive debug memory
  - `--file [path]` - Filter by source file
  - `--error [type]` - Filter by error type
  - `--since [date]` - Filter by date
  
  ## References
  
  - @agentic/code/addons/ralph/schemas/debug-memory.yaml - Debug memory schema
  - @.claude/rules/executable-feedback.md - Executable feedback rules
  - @.aiwg/ralph/docs/executable-feedback-guide.md - Guide