name: execute-tests-on-generated-code-and-iterate-until-passing
description: Execute tests on generated code and iterate until passing
model:
  name: gpt-4
  temperature: 0.3
  max_tokens: 4000
instructions: |
  # Execute Feedback Command
  
  Run executable feedback loop on generated code: execute tests, analyze failures, fix, and retry.
  
  ## Instructions
  
  When invoked, perform the executable feedback loop per REF-013 MetaGPT:
  
  1. **Identify Target**
     - Load the specified file or recently modified code files
     - Determine test framework (jest, pytest, cargo test, go test, etc.)
     - Find existing tests or generate test stubs if none exist
  
  2. **Execute Tests**
     - Run the specified test command (or auto-detect)
     - Capture full output (stdout, stderr, exit code)
     - Parse test results: passed, failed, errors, skipped
  
  3. **Analyze Failures**
     - For each failing test:
       - Extract error type and message
       - Identify root cause (null check, type error, logic error, etc.)
       - Map to source code location
     - Check debug memory for similar past failures
  
  4. **Apply Fixes**
     - Generate targeted fix based on root cause analysis
     - Apply fix to source code
     - Increment attempt counter
  
  5. **Re-Execute**
     - Run tests again after fix
     - Compare results to previous attempt
     - If all pass: record success in debug memory, return
     - If still failing: repeat from step 3
  
  6. **Escalate if Needed**
     - After max attempts (default: 3), escalate to human
     - Include: all test results, failure analyses, fix attempts
     - Save debug memory session
  
  7. **Update Debug Memory**
     - Record execution session in `.aiwg/ralph/debug-memory/sessions/`
     - Extract learned patterns to `.aiwg/ralph/debug-memory/patterns/`
     - Update success metrics
  
  ## Arguments
  
  - `[file-path]` - Source file to test (default: recently modified files)
  - `--test-command [cmd]` - Test command to run (default: auto-detect)
  - `--max-attempts [n]` - Maximum fix attempts (default: 3)
  - `--coverage [%]` - Minimum coverage target (default: 80)
  - `--no-fix` - Run tests only, report without fixing
  - `--verbose` - Show full test output
  
  ## References
  
  - @.claude/rules/executable-feedback.md - Executable feedback rules
  - @.aiwg/ralph/docs/executable-feedback-guide.md - Implementation guide
  - @agentic/code/addons/ralph/schemas/debug-memory.yaml - Debug memory schema
  - @agentic/code/frameworks/sdlc-complete/schemas/flows/executable-feedback.yaml - Workflow schema
  - @.aiwg/research/findings/REF-013-metagpt.md - Research foundation